twpayne/go-geom

- encoding/geojson/geojson.go
- encoding/geojson/geojson_test.go
Replace `Encode` and `Decode` with `encoding/json`-like `Marshal` and `Unmarshal`.
> Refactor GeoJSON support

- xy/area_centroid.go
- xy/area_centroid_test.go
- xy/centroid.go
- xy/centroid_test.go
- xy/line_centroid.go
- xy/line_centroid_examples_test.go
- xy/line_centroid_test.go
- xy/point_centroid.go
- xy/point_centroid_examples_test.go
- xy/point_centroid_test.go
Added method for calculating the centroid of a generic geometry (geom.T) in 2d space
> Added method for calculating the centroid of a generic geometry

- encoding/geojson/geojson.go
when encoding Geometry in actual json, using UnmarshalJSON , the coordinates field is render as a string instead of the actual object. This is because the UnmarshallJSON is not the same on json.RawMessage and *json.RawMessage. 
changing the field by a pointer is a quick workaround.
The other one could be to create function UnmarshalJSON and MarshalJSON for the GeometryType ...
> Marshall json geometry

- encoding/ewkb/ewkb.go
- encoding/wkbcommon/binary.go
This completes @kostub's performance improvements in #48 for EWKB.
> Improve EWKB decode performance

- encoding/igc/decode.go
> igc: Parse negative values

- encoding/geojson/geojson.go
- encoding/geojson/geojson_test.go
> Handle nil coordinates in GeoJSON

- encoding/ewkb/ewkb.go
- encoding/ewkb/postgis_test.go
- encoding/wkb/wkb.go
> wkb, ewkb: add documentation note about binary_parameters

- flat_geom0.go
- flat_geom1.go
- flat_geom2.go
- flat_geom3.go
- geom_test.go
- linearring.go
- linestring.go
- linestring_test.go
- multilinestring.go
- multipoint.go
- multipolygon.go
- point.go
- point_test.go
- polygon.go
This boosts the test coverage, and adds a small cleanup.
> Add more tests

- xy/cga.go
- xy/cga_examples_test.go
- xy/cga_test.go
- xy/convex_hull.go
- xy/convex_hull_examples_test.go
- xy/convex_hull_test.go
- xy/internal/raycrossing/ray-crossing-counter.go
- xy/internal/raycrossing/ray_crossing_test.go
- xy/internal/robustdeterminate/robust_determinate.go
- xy/internal/robustdeterminate/robust_determinate_test.go
Per https://github.com/locationtech/jts/blob/master/modules/core/src/main/java/org/locationtech/jts/algorithm/RobustDeterminant.java#L23
It's licensed under EPL
> restore Robust sign

- xy/rdp_simplify.go
- xy/rdp_simplify_test.go
> add rdp simplify

- encoding/geojson/geojson.go
- encoding/geojson/geojson_test.go
> Support null geometries

- encoding/wkt/decode.go
- encoding/wkt/encode.go
- encoding/wkt/wkt.go
- encoding/wkt/wkt_test.go
- linestring.go
- point.go
- polygon.go
Fix for issue #47 (Support for WKT)
> Added WKT decoding (Support for WKT #47)

- encoding/wkt/decode.go
- encoding/wkt/wkt.go
- encoding/wkt/wkt_test.go
- flat.go
- linearring.go
- linestring.go
- multilinestring.go
- multipoint.go
- multipolygon.go
- point.go
- polygon.go
> WKT clean-ups

- encoding/geojson/geojson.go
- encoding/geojson/geojson_test.go
In PostGIS, the bbox and CRS fields are supported in the GeoJSON
encoding, e.g.:
```
otan=# select st_asgeojson('multilinestring ((1.0 1.0, 2.0 2.0), (4.0 4.0, 5.0 5.0))'::geography, 2, 3);
st_asgeojson
-------------------------------------------------------------------------------------------------------------------------------------------------------------
{"type":"MultiLineString","crs":{"type":"name","properties":{"name":"EPSG:4326"}},"bbox":[1.00,1.00,5.00,5.00],"coordinates":[[[1,1],[2,2]],[[4,4],[5,5]]]}
(1 row)
```
Allow the same behaviour by adding the `EncodeGeometryOption` optional
arguments to Marshal and Encode.
> encoding/geojson: add CRS and BBox fields to the Geometry encoding

- encoding/geojson/geojson.go
- encoding/geojson/geojson_test.go
Add support for maximum decimal digits being output in a GeoJSON. This
involved some trickery with implementing `MarshalJSON` on a slice of
coords that could be `[]float64`, `[][]float64` or `[][][]float64`. This
logic is also applied to the bounding box object if desired.
Also fix the encode bbox option to automatically figure out the bounds
from the provided geom.T object.
I notice there has been no release tag yet so this should be safe to go
into the wild.
> encoding/geojson: support maxDecimalDigits

- bigxy/big_cga_test.go
- sorting/sorting_test.go
- transform/transform_test.go
- transform/tree_set_test.go
Doing these bit by bit; here's a bunch.
> bigxy, sorting, transform: convert to testify for tests

- geom.go
- geom_test.go
> Add TransformInPlace

- .golangci.yml
- Makefile
- README.md
- bigxy/big_cga.go
- geom.go
- xy/cga_test.go
- xy/lineintersector/nonrobust_line_intersector.go
- xy/lineintersector/robust_line_intersector.go
This cleans up a bit of bitrot.
> Update build infrastructure

- geom.go
- geom_test.go
- geometrycollection_test.go
- linearring_test.go
- linestring_test.go
- multilinestring_test.go
- multipoint_test.go
- multipolygon_test.go
- point_test.go
- polygon_test.go
> Add top level SetSRID function

- geomtest/geomtest.go
- xy/area_centroid.go
- xy/area_centroid_test.go
- xy/centroid_test.go
- xy/cga.go
- xy/cga_test.go
- xy/internal/cga.go
- xy/internal/hcoords/hcoords.go
- xy/line_centroid.go
- xy/line_centroid_examples_test.go
- xy/line_centroid_test.go
- xy/lineintersector/nonrobust_line_intersector.go
- xy/lineintersector/robust_line_intersector_test.go
- xyz/vector.go
- xyz/vector_test.go
- xyz/xyz.go
- xyz/xyz_test.go
> Tolerate minor differences in floating point results to support FMA

- encoding/geojson/geojson.go
- encoding/geojson/geojson_test.go
> GeoJSON tweaks

- flat.go
- geom_test.go
- polygon_test.go
> Fix area calculation for polygons with holes
