twpayne/go-geom

.travis.yml
See https://docs.travis-ci.com/user/migrating-from-legacy/
=> Flag lack of need for root access to enable faster Travis builds

geom.go, linearring.go, linestring.go, multilinestring.go, multipoint.go, multipolygon.go, point.go, polygon.go
This PR replaces `MustSetCoords` with an abstract function ` func Must(g T, err error) T` to which the return value of `SetCoords` can be used as an argument.
This has the advantage of extensibility: it is very likely that we'll add more functions that take a `T` and some other arguments in the future and return a new or updated `T` and an `error`. This saves us having to write a `MustDoFoo` convenience function for every `DoFoo` function that we write.
The downside here is that we're really suffering from Go's lack of generics and its primitive type system. Every call to `Must` strips type information, and this type information occasionally needs to be reinstated with a type assertion. Yuk.
@jesseeichar What do you think about this? Nice abstraction or too messy and complex for Go?
=> Abstract out Must and remove MustSetCoords

encoding/wkb/wkb.go, encoding/wkb/wkb_test.go, encoding/wkbcommon/binary.go, encoding/wkbcommon/wkbcommon.go
It turns out that using `binary.Read` and `binary.Write` is quite slow. Significant performance gains can be achieved by using `byteOrder.Uint64` and `byteOrder.PutUint64`.
Here are some benchmarks:
Before my change:
```
BenchmarkUnmarshal-4   	    5000       	    230946 ns/op       	  133568 B/op  	    2290 allocs/op
BenchmarkMarshal-4     	   10000       	    231463 ns/op       	   87008 B/op  	    1753 allocs/op
```
After my change:
```
BenchmarkUnmarshal-4   	   10000       	    140244 ns/op       	  120400 B/op  	    1542 allocs/op
BenchmarkMarshal-4     	   10000       	    117554 ns/op       	   73776 B/op  	    1005 allocs/op
```
=> Optimize the performance of Marshal/Unmarshal for WKB

encoding/ewkb/postgis_test.go
Adds a query parameter to the PostGIS integration test to better illustrate #65.
Test currently fails. Can be fixed by appending `&binary_parameters=yes` to the connection string.
Without binary_parameters:
```
$ go test -tags integration -v postgis_test.go
=== RUN   TestPostGIS
--- FAIL: TestPostGIS (0.04s)
postgis_test.go:43: db.QueryRow(...).Scan(...) == pq: invalid byte sequence for encoding "UTF8": 0x00, want <nil>
FAIL
exit status 1
FAIL	command-line-arguments	0.045s
```
With binary_parameters:
```
$ go test -tags integration -v postgis_test.go
=== RUN   TestPostGIS
--- PASS: TestPostGIS (0.04s)
PASS
ok  	command-line-arguments	0.052s
```
=> Add query parameter to PostGIS integration test

flat_geom0.go, flat_geom1.go, flat_geom2.go, flat_geom3.go, geometrycollection.go, linearring.go, linestring.go, multilinestring.go, multipoint.go, multipolygon.go, point.go, polygon.go
- Document more exported functions
- Use `g` as the receiver name everywhere.
- Fix a copy-and-paste error in `LinearRing.Area`
=> Documentation improvements

encoding/ewkbhex/ewkbhex.go, encoding/wkbhex/wkbhex.go
This reduces the number of imports needed by users when using hex formats.
=> Export WKB encodings

encoding/geojson/geojson.go
The `Unmarshal` function used `MustSetCoord` and duplicated `Geometry.Decode`. Also, the `FeatureCollection` now checks for the correct `Type` field when unmarshaling.
=> geojson: improve error handling

encoding/geojson/geojson.go, encoding/geojson/geojson_test.go
I tried to paste some marshalled features into http://geojson.io and it gave me a bunch of errors
According to the spec:
* `feature.properties`  must be present, but can be `null`.
* `feature.geometry` must always be present.
* `feature.type` must always be present.
* `feature_collection.features` must be an array, but can be empty.
=> geojson: never omit properties or type

.travis.yml, encoding/ewkb/sql_example_test.go, encoding/wkb/sql_test.go, go.mod, go.sum
The module name for datadog is `github.com/DATA-DOG/go-sqlmock`
https://github.com/DATA-DOG/go-sqlmock/commit/472e287dbafe67e526a3797165b64cb14f34705a
When I tried to add this library to a go modules project, it was failing with a message about invalid import paths.
```shellsession
$ go get -u github.com/twpayne/go-geom
go: finding github.com/twpayne/go-geom v1.0.4
go: gopkg.in/DATA-DOG/go-sqlmock.v1@v1.3.2: go.mod has non-....v1 module path "github.com/DATA-DOG/go-sqlmock" at revision v1.3.2
go get: error loading module requirements
```
So I figured with go.mod we already specify a minimum version, so it can just not use gopkg.in
Signed-off-by: Ivan Porto Carrero <ivan@oneconcern.com>
=> move to actual module for sqlmock

encoding/geojson/geojson.go, encoding/geojson/geojson_test.go
This adds bounding box support as described in the [geojson spec](https://tools.ietf.org/html/rfc7946#section-5).
I wasn't sure if you'd want me to add more errors, I noticed that there's only 2 kinds of errors in geojson.go at the moment but I could potentially add 3 more for this change (on lines 310 and 325, and at the top of encodeBoundingBox for if the Bounds is empty or nil).
=> Added Bounding Box support to geojson encoding

.golangci.yml, Makefile, encoding/ewkb/ewkb_test.go, encoding/ewkbhex/ewkbhex_test.go, encoding/wkb/wkb_test.go
* Upgrade to v1.25.0, which prevents the bad interface check.
* Added godot, nestif, testpackage, which was failing before this
commit.
* Fix goimports formatting.
=> golangci-lint: fix lint failing on master

encoding/ewkb/ewkb.go, encoding/ewkb/ewkb_test.go, encoding/wkb/wkb.go, encoding/wkb/wkb_test.go
This follows the WKT encoding protocol allowing GEOMETRYCOLLECTION EMPTY to be written as WKB and EWKB.
cc https://github.com/cockroachdb/cockroach/issues/48533
=> encoding: support GEOMETRYCOLLECTION EMPTY wkb/ewkb writes

geom.go, geometrycollection.go, geometrycollection_test.go, linearring_test.go, linestring_test.go, multilinestring_test.go, multipoint_test.go, multipolygon_test.go, point_test.go, polygon_test.go
* Add Empty() to the T interface, which is defined on all geom.T types.
* Add interface assertions for all the types, makes unimplemented
interface errors easier to read at compile time.
* In PostGIS (at least), its possible for a GeometryCollection to have
multiple Empty elements and still be considered empty, e.g.
`GEOMETRYCOLLECTION(POINT EMPTY, LINESTRING EMPTY)`. This check changes
the Empty check such that GeometryCollection's Empty() also checks for
these cases.
=> add Empty to T interface and correct Empty for GeometryCollection

flat.go, multilinestring.go, multilinestring_test.go, multipolygon.go, multipolygon_test.go
MultiLineString / MultiPolygon should be to handle extreme cases such as
MULTILINESTRING (EMPTY, EMPTY) or MULTIPOLYGON (EMPTY, POLYGON(1.0...)).
This PR adapts the code to make this happen. This is compliant with the `ST_IsEmpty` definition.
----
Unfortunately, it will not work for MultiPoint. I'm guessing this is the
reason the spec has:
```
If the geometry is a Point, it SHALL be encoded with each coordinate value set to an IEEE-754 quiet NaN value. GeoPackages SHALL use big endian 0x7ff8000000000000 or little endian 0x000000000000f87f as the binary encoding of the NaN values. (This is because Well-Known Binary as defined in OGC 06-103r4 [9] does not provide a standardized encoding for an empty point set, i.e., 'Point Empty' in Well-Known Text.)
```
It is impossible to tell between …
=> fix MultiPolygon and MultiLineString to handle EMPTY sub-geometries

encoding/ewkb/ewkb.go, encoding/wkb/wkb.go
Previously, if you had `geom.NewPointFlat(geom.NoLayout)`, and tried to
cast it to a WKB or EWKB, a panic would occur instead of invalid layout for
non-GeometryCollections.
This is because the `g` argument would become `nil` and hence
`g.Layout()` would be a nil dereference. Fix that up by not reassigning
`g` (as Empty() is now part of the interface so we don't need it
dereferenced).
(this was my bad :P)
=> encoding/*wkb: fix panic on invalid layout on empty geometries

encoding/wkt/encode.go, encoding/wkt/wkt.go, encoding/wkt/wkt_test.go
This commit adds support for maximum decimal digits in WKT encoding,
similar to the way PostGIS handles ST_AsText(<geom>, <maxdecimaldigits>).
We have to do extra processing to remove trailing 0 and . marks.
To make this change, we also expose "Encoder" as a struct, with the
Encode object made public. This can take in `EncodeOption`s which allow
an arbitrary amount of options in a clean way.
=> encoding/wkt: expose maxDecimalDigits as an option

encoding/geojson/geojson.go, encoding/geojson/geojson_test.go, encoding/wkt/encode.go, encoding/wkt/wkt_test.go
My bad - found these whilst integrating with a few things.
* For GeoJSON, we didn't truncate the trailing 0's and `.`.
* For WKT, we incorrectly pruned trailing 0's for maxDecimalDigits = 0,
so items like "10" become "1".
=> encoding: fix maxDecimalDigits truncation

encoding/ewkb/ewkb.go, encoding/ewkb/ewkb_test.go, encoding/wkb/sql.go, encoding/wkb/wkb.go, encoding/wkb/wkb_test.go, encoding/wkbcommon/binary.go, encoding/wkbcommon/options.go, encoding/wkbhex/wkbhex.go, encoding/wkbhex/wkbhex_test.go, point.go
For EWKB, NaNs will now encode and decode as EMPTY points.
For WKB, we specify an option to encode and decode points as empty with
NaNs. If not set, NaN points will encode as an error, and decode with
coordinates of (NaN, NaN...).
Resolves #164.
=> encoding/*wkb: handle EMPTY POINT NaN encoding

encoding/geojson/geojson.go, encoding/geojson/geojson_test.go, point.go
* For EMPTY points, the EMPTY point should still display with values
`[]`, analogous to PostGIS.
* For EMPTY GeometryCollections, geometries were omitted but the field
`geometries` should still be included.
=> encoding/geojson: correctly handle POINT EMPTY

encoding/wkb/sql.go
wkbcommon.ErrUnexpectedType.Got is filled with the result of the type
assertion, while it should receive the source of it.
When the type assertion failed, the first returned value is just an
empty expected type. Using it in Got makes error message like :
wkb: got *geom.Point, want *wkb.Point
which is really misleading. With this commit, the error message looks
like :
wkb: got *geom.Polygon, want *wkb.Point
which has a lot more sense, we immediately understand the problem is
because of wrong geography kinds.
=> encoding/wkb: fix misleading error message

bounds_test.go, geom_test.go, geometrycollection_test.go, linearring_test.go, linestring_test.go, multilinestring_test.go, multipoint_test.go, multipolygon_test.go, point_test.go, polygon_test.go
This PR moves to `github.com/stretchr/testify` for tests, which is significantly easier to use that Go's standard `testing` library, and provides nicer error messages when complex values differ.
Not all tests are ported yet.
=> Use github.com/stretchr/testify

encoding/wkb/sql.go, encoding/wkb/sql_example_test.go
When the shape of a geometry isn't defined (for example when you use the
GEOMETRY postgis type), you can't use the scanners defined in
encoding/wkb, you have to iterate over the results and invoke
wkb.Marshal on the column.
This change introduces a new type wkb.Geom which can scan any kind of
geometry shape.
I've added NOTEs about details I would like to discuss, please review
them.
I've also added new examples to illustrate the usage, tell me if the
example names are OK for you.
=> encoding/wkb: new type Geom

encoding/geojson/geojson.go
In Go 1.15, [integers must be explicitly cast to runes](https://golang.org/doc/go1.15#vet) before being cast to strings, to avoid `go vet` errors. These are enabled by default on `go test`, causing test failures.
=> geojson: fix rune cast for Go 1.15

encoding/wkt/decode.go, encoding/wkt/encode.go, encoding/wkt/wkt_test.go
WKT encoding of collections with empty elements resulted in empty collections. Consider the following geometry:
```golang
geom.NewGeometryCollection().MustPush(
geom.NewPointEmpty(geom.XY),
geom.NewLineString(geom.XY),
)
```
Which resulted in the following encoding:
```
GEOMETRYCOLLECTION EMPTY
```
While the correct encoding is:
```
GEOMETRYCOLLECTION (POINT EMPTY, LINESTRING EMPTY)
```
The same was true for all multi-types.
This also fixes decoding of the corresponding WKT. The decoder is rather brittle, but the test cases pass at least.
=> encoding/wkt: fix handling of collections with empty elements

flat.go, geom_test.go
This PR adds a Reverse method to geom1, geom2 and geom3. It implements an in-place reversal of linear coordinate order while maintaining sub-structure order. Tests are included for multiple geometry types. Ref #118.
=> Add Reverse

xy/convex_hull.go, xy/convex_hull_test.go
Fixes #146. Prior to this, if each point in the Akl-Toussaint heursitic octogon was unique the reduction was guaranteed to panic on out-of-bounds array access.
This changes avoids that panic by building a new slice of deduped octogon points.
=> Fix common-case panic in convex hull calculation.

xy/lineintersector/nonrobust_line_intersector.go
This was exposed while testing CockroachDB.
The geomfn/TestShortestLineString fails due to floating point precision differences caused by FMA on ppc64le.
See https://go.dev/ref/spec#Floating_point_operators for more details.
=> Fix floating point precision failure caused by FMA on ppc64le

xy/area_centroid.go, xy/cga.go, xy/internal/cga.go, xy/internal/hcoords/hcoords.go, xy/line_centroid.go, xyz/vector.go, xyz/xyz.go
Following tests fail on ppc64le due to FMA:
xy
- TestAreaGetCentroid
- TestCentroid
- TestSignedArea
- TestLineGetCentroidLines
- TestLineGetCentroidPolygons
- ExampleLinearRingsCentroid
xy/lineintersector
- TestRobustLineIntersectionLines
xyz
- TestVectorDot
- TestVectorLength
- TestDistanceLineToLine
- TestDistancePointToLine
See https://go.dev/ref/spec#Floating_point_operators for more details.
=> Fix floating point precision failures caused by FMA on ppc64le

encoding/wkt/lex.go, encoding/wkt/wkt_test.go
From PostGIS:
```
postgis=# SELECT ST_IsClosed('POLYGON ZM ((0 0 0 0, 1 0 -1 1, 1 1 -2 2, 0 0 0 3))'::geometry);
st_isclosed
-------------
t
(1 row)
```
Note that the polygon is considered closed, even though the M coordinates of the first and last points differ.
=> Don't consider coordinates beyond Z when testing for polygon closure

encoding/geojson/geojson.go, encoding/geojson/geojson_test.go
This PR provides backward compatibility although with that requirement I think we cannot preserve ID type information after Marshal - Unmarshal (number would become string).
So this is a kind of workaround. All tests pass and my own project works with this code.
=> Support for numbers as `Feature.ID`

encoding/geojson/geojson.go
A double pointer is needed here to pass through null as nil.
Note that the tests still pass after this change.
=> Fix lint warning in GeoJSON unmarshaling
